package anaxxes.com.weatherFlow.admob

enum class Rewarded {
    ON_REWARDED, ON_REWARDED_VIDEO_AD_LEFT_APP, ON_REWARDED_VIDEO_AD_CLOSED, ON_REWARDED_VIDEO_AD_FAILED_TO_LOAD, ON_REWARDED_VIDEO_AD_LOADED, ON_REWARDED_VIDEO_AD_OPENED, ON_REWARDED_VIDEO_STARTED, ON_REWARDED_AD_COMPLETED
}